### PR TITLE
Adds new vendor information to the PCI file

### PR DESCRIPTION
**Pull request by UOS-Python**
0731  Jingjia Microelectronics Co Ltd

### CODE REVIEW

**Comment by wfeldt** [comment]
Sorry, this slipped my attention. I've created https://github.com/openSUSE/hwinfo/pull/98 to update the PCI and USB ids to their latest versions. AFAICS, your change is included.

**Comment by UOS-Python** [comment]
Thank you very much,I am a C++ engineer from Tongxin Software Technology Co., Ltd.  A Chinese company that develops an operating system, UOS .
Our company was formerly known as Deepin ，If you haven't heard of us(Deepin), you can read about us here https://www.deepin.org/zh .

**Comment by UOS-Python** [comment]
> Sorry, this slipped my attention. I've created #98 to update the PCI and USB ids to their latest versions. AFAICS, your change is included.

Thank you very much. I am a C++ engineer from Tongxin Software Technology Co., Ltd. A Chinese company that develops an operating system, UOS .
Our company was formerly known as Deepin ，If you haven't heard of us(Deepin), you can read about us here https://www.deepin.org/zh .

**Comment by UOS-Python** [comment]
> Sorry, this slipped my attention. I've created #98 to update the PCI and USB ids to their latest versions. AFAICS, your change is included.

I believe I will continue to offer patch to you

**Pull request closed without merging**
