### PR TITLE
Donot close the open tray after read.

### PR DESCRIPTION
**Pull request by yangbonis**
hwinfo --cdrom can close the open tray, correct it

### CODE REVIEW

**Comment by yangbonis** [comment]
@dmacvicar

**Comment by wfeldt** [comment]
`is.notready` should still be 1 if open() fails. Maybe start with `is.notready = 1` and set it to 0 if `ioctl(..) == CDS_DISC_OK`?

**Comment by yangbonis** [comment]
> `is.notready` should still be 1 if open() fails. Maybe start with `is.notready = 1` and set it to 0 if `ioctl(..) == CDS_DISC_OK`?

you are right, already update.

**Review by wfeldt — APPROVED** [review]

**Comment by wfeldt** [comment]
You're absolutely right; please check https://github.com/openSUSE/hwinfo/pull/109.

**Pull request merged**
